### PR TITLE
Clear error msg

### LINKED ISSUE #33: [Feature]: Show clear error message when API calls fail
### Description

Currently, when API calls fail, we have these error message
Capture d’écran 2022-10-14 à 10 51 36

Could we have a clearer message with at least error code

### PR DESCRIPTION
**Pull request by outscale-mdr**
Before we add error message like that
Capture d’écran 2022-10-14 à 17 02 07

Now, we have a clearer message
Capture d’écran 2022-10-14 à 16 34 10
and the user can retrieve the request id from the debug console
Capture d’écran 2022-10-14 à 16 34 24

Closes #33

### CODE REVIEW

File: src/cloud/accesskeys.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function getAccessKeys(profile: Profile, filters?: FiltersAccessKeys): Pr
         }
         return res.accessKeys;
     }, (err_: any) => {
-        return "Error, bad credential or region?" + err_;
+        return err_;
```
Comment (jerome-jutteau) [inline src/cloud/accesskeys.ts:28]: just a comment, not blocker: "_" is used to mean non-used variables, maybe you can just name it "err"

**Review by jerome-jutteau — APPROVED** [review]
